sonar.projectKey=omnistream-g8
sonar.working.directory=C:\\Users\\Danie\\OmniStream\\.sonarqube\\out\\.sonar
sonar.projectBaseDir=C:\\Users\\Danie\\OmniStream
sonar.pullrequest.cache.basepath=C:\\Users\\Danie\\OmniStream
sonar.sources=\
"C:\\Users\\Danie\\OmniStream\\PresentacionCLI\\usuarios.json",\
"C:\\Users\\Danie\\OmniStream\\Infraestructura\\obj\\Infraestructura.csproj.nuget.dgspec.json",\
"C:\\Users\\Danie\\OmniStream\\Infraestructura\\obj\\project.assets.json",\
"C:\\Users\\Danie\\OmniStream\\PresentacionCLI\\obj\\PresentacionCLI.csproj.nuget.dgspec.json",\
"C:\\Users\\Danie\\OmniStream\\PresentacionCLI\\obj\\project.assets.json",\
"C:\\Users\\Danie\\OmniStream\\Tests\\obj\\project.assets.json",\
"C:\\Users\\Danie\\OmniStream\\Tests\\obj\\Tests.csproj.nuget.dgspec.json",\
"C:\\Users\\Danie\\OmniStream\\Infraestructura\\bin\\Debug\\net10.0\\Infraestructura.deps.json",\
"C:\\Users\\Danie\\OmniStream\\Infraestructura\\obj\\Debug\\net10.0\\Infraestructura.sourcelink.json",\
"C:\\Users\\Danie\\OmniStream\\PresentacionCLI\\bin\\Debug\\net10.0\\PresentacionCLI.deps.json",\
"C:\\Users\\Danie\\OmniStream\\PresentacionCLI\\bin\\Debug\\net10.0\\PresentacionCLI.runtimeconfig.json",\
"C:\\Users\\Danie\\OmniStream\\PresentacionCLI\\obj\\Debug\\net10.0\\PresentacionCLI.sourcelink.json",\
"C:\\Users\\Danie\\OmniStream\\Tests\\bin\\Debug\\net10.0\\Tests.deps.json",\
"C:\\Users\\Danie\\OmniStream\\Tests\\bin\\Debug\\net10.0\\Tests.runtimeconfig.json",\
"C:\\Users\\Danie\\OmniStream\\Tests\\obj\\Debug\\net10.0\\Tests.sourcelink.json"

12F3CF19-F88C-0774-969F-8840F52C7312.sonar.projectKey=omnistream-g8:12F3CF19-F88C-0774-969F-8840F52C7312
12F3CF19-F88C-0774-969F-8840F52C7312.sonar.projectName=Dominio
12F3CF19-F88C-0774-969F-8840F52C7312.sonar.projectBaseDir=C:\\Users\\Danie\\OmniStream\\Dominio
12F3CF19-F88C-0774-969F-8840F52C7312.sonar.sourceEncoding=utf-8
12F3CF19-F88C-0774-969F-8840F52C7312.sonar.tests=
12F3CF19-F88C-0774-969F-8840F52C7312.sonar.sources=\
"C:\\Users\\Danie\\OmniStream\\Dominio\\Class1.cs",\
"C:\\Users\\Danie\\OmniStream\\Dominio\\IUsuarioRepositorio.cs",\
"C:\\Users\\Danie\\OmniStream\\Dominio\\MotorDescuentos.cs",\
"C:\\Users\\Danie\\OmniStream\\Dominio\\ServicioSuscripcion.cs",\
"C:\\Users\\Danie\\OmniStream\\Dominio\\Usuario.cs",\
"C:\\Users\\Danie\\OmniStream\\Dominio\\obj\\Dominio.csproj.nuget.dgspec.json",\
"C:\\Users\\Danie\\OmniStream\\Dominio\\obj\\project.assets.json",\
"C:\\Users\\Danie\\OmniStream\\Dominio\\bin\\Debug\\net10.0\\Dominio.deps.json",\
"C:\\Users\\Danie\\OmniStream\\Dominio\\obj\\Debug\\net10.0\\Dominio.sourcelink.json"

12F3CF19-F88C-0774-969F-8840F52C7312.sonar.cs.analyzer.projectOutPaths=\
"C:\\Users\\Danie\\OmniStream\\.sonarqube\\out\\0"
12F3CF19-F88C-0774-969F-8840F52C7312.sonar.cs.roslyn.reportFilePaths=\
"C:\\Users\\Danie\\OmniStream\\.sonarqube\\out\\0\\Issues.json"
12F3CF19-F88C-0774-969F-8840F52C7312.sonar.cs.scanner.telemetry=\
"C:\\Users\\Danie\\OmniStream\\.sonarqube\\out\\0\\Telemetry.json"

12F3CF19-F88C-0774-969F-8840F52C7312.sonar.working.directory=C:\\Users\\Danie\\OmniStream\\.sonarqube\\out\\.sonar\\mod0
sonar.host.url=http://localhost:9000
sonar.visualstudio.enable=false

sonar.modules=12F3CF19-F88C-0774-969F-8840F52C7312

